services:
    av_list:
        class: AppVentus\ListBundle\Component\AvListFactory
        arguments: [@request, @templating]
        public: true
        scope: request

    av_list.twig.list_extension:
        class: AppVentus\ListBundle\Twig\Extension\ListExtension
        arguments: [@twig]
        tags:
            - { name: twig.extension }
